### PR TITLE
Added a compatlayer version of IRecipe 1.11.2

### PR DESCRIPTION
**Pull request by chazwarp923**

### CODE REVIEW

**Comment by McJty** [comment]
BTW. I'm going to make a few changes. i.e. I'll make CompatIRecipe an interface with default's so that you can still implement it together with other classes

**Comment by chazwarp923** [comment]
I'm fine with that, I just tried to make an implementation I knew was gonna work without having to do a whole bunch of back and forth like last time.

**Comment by chazwarp923** [comment]
Okay, so I'm testing your changes and it seems you over looked the fact that ItemStackList extends NonNullList. So when i compile on 1.11 it references NNL which if then loaded in 1.10 crashes.

**Comment by chazwarp923** [comment]
Never mind I'm an idiot and was overriding the same method i need to replace with the compat version.

**Pull request merged**
